language: go
go:
- master
install:
- go get github.com/spf13/hugo
- git clone --depth 1 --recursive https://github.com/bul-ikana/hugo-cards.git blog/themes/hugo-cards
script:
- cd blog && hugo
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: blog/public/
  on:
    branch: master
env:
  global:
    secure: lVaKBBknJMEZ/h7wt1yNkHNVathaSV6fMo5krraKdai4ziXK2bPrugmJmusH/QRxDuJyNkUPjgawHuHBhHTrQ77XzTH0Ozv+sgID6OjSfLg0+xMEFvE6dOS1YTnNci6/h026pg97RmhgUSopiu9Ke1YihQhoICdXmXtx0HyGcqPJQbgQMwkioIXtaUIpX9P1kyV9FM4lxDJdv6DV/I0evzM5clgzNL4qqLJleMJpYroyPFgUSdb5gysZ+dNp37EsDyp2+o4un3h8yfXgDuJJ1DNsfV/CYGsTImoBcfSeGIdG3oqgs1ROKxiOK8KH89KqF6pVl+ullzBWRCjewKwOJL8Zxzxt3mNYU3fHCIJMkDH+7o+oWMNLtxeUUSecu31Yx6qC9MexU6SwWBf3bEzZCv0O9eF6OLZG28Mmww6alx2Hp1Gw+shXS09WIk9VPwddHIJlENyGjTSprrbXEbLzw5mX10zIpWmJsJH7Gf0h3Iz6vN4dBibn52LTn363qrokpvu3KtLt6DhScPaP9Mdw7RMrY3CZX2OyGjAD963OsCo3wU4v2qfVtJOGoL3+CBPW4cyp0N0f/5qbDj71G1/fRwpjvGviJ3pYmV7c4tgu6rTtnCG6xhudrb7uIYlk/yJtUSVAPYBUBP18QRZmYvcgukcJne2S9NeqzkrEVbK1klw=
