baseURL = "https://nolte.github.io/minecraft-gameserver/"
languageCode = "de"
title = "Minecraft GameServer"
theme = "hugo-cards"
paginate = 6
disqusShortname = "minecraft-gameserver"

[params]
  builtBy = "nolte"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = ""
  github = "http://github.com/nolte"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  analytics = ""

  disqusShortname = "minecraft-gameserver"
  disqus = "minecraft-gameserver"

  [params.copyright]
     name = "nolte"
     link = "http://github.com/nolte"

[taxonomies]
  category = "categories"
  tag = "tags"


[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
